version: '3.4'

services:
  cryptocatbackend:
    image: cryptocatbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
