version: '3.4'

services:
  cryptocat-backend:
    container_name: cryptocat-backend
    image: cryptocat-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    networks:
      - sub-etha
  cryptocat-frontend:
    container_name: cryptocat-frontend
    image: cryptocat-frontend
    build: ../cryptocat-frontend
    networks:
      - sub-etha
    ports:
      - 80:80

networks:
  sub-etha:
